.Dd 2022-04-25
.Dt BRICK 1
.Sh NAME
.Nm brick
.Nm bricks
.Nd simple static web server
.Sh SYNOPSIS
.Nm
.Ar ca-file
.Ar cert-file
.Ar key-file
.Sh DESCRIPTION
.Nm
is a simple HTTP web server for static content.
.Sh OPTIONS
.Bl -tag -width Ds
.El
.Sh AUTHORS
.An Thomas Oltmann Aq Mt thomas.oltmann.hhg@gmail.com
